---
# tasks file for ansible-role-nfsv4-server-freebsd

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ nfsv4-server-freebsd_log_dir }}"
    mode: 0755
    owner: "{{ nfsv4-server-freebsd_user }}"
    group: "{{ nfsv4-server-freebsd_group }}"
    state: directory
  notify: Restart nfsv4-server-freebsd

- name: Create db directory
  file:
    path: "{{ nfsv4-server-freebsd_db_dir }}"
    mode: 0755
    owner: "{{ nfsv4-server-freebsd_user }}"
    group: "{{ nfsv4-server-freebsd_group }}"
    state: directory
  notify: Restart nfsv4-server-freebsd

- name: Create nfsv4-server-freebsd.conf
  template:
    src: nfsv4-server-freebsd.conf.j2
    dest: "{{ nfsv4-server-freebsd_conf_file }}"
    validate: echo %s
  notify: Restart nfsv4-server-freebsd

- name: Start nfsv4-server-freebsd
  service:
    name: "{{ nfsv4-server-freebsd_service }}"
    enabled: true
    state: started
