---

- name: Restart mountd
  service:
    name: mountd
    state: restarted

- name: Reload mountd
  service:
    name: mountd
    state: reloaded

- name: Restart nfsd
  service:
    name: nfsd
    state: restarted

- name: Restart rpcbind
  service:
    name: rpcbind
    state: restarted
  notify:
    - Restart mountd
    - Restart nfsd

- name: Restart nfsuserd
  service:
    name: nfsuserd
    state: restarted
